UnicornCreations/UnicornCreations/Controllers/MembershipController.cs
using System.Web.Mvc;
using System.Web.Security;

namespace UnicornCreations.Controllers
{
	public class MembershipController : Controller
	{
		public MembershipController(IFormsAuthenticationService formsService, IMembershipService membershipService)
		{
			FormsService = formsService;
			MembershipService = membershipService;
		}

		public IFormsAuthenticationService FormsService { get; set; }
		public IMembershipService MembershipService { get; set; }

		// **************************************
		// URL: /Account/LogOn
		// **************************************

		public ActionResult LogOn()
		{
			return View();
		}

		[HttpPost]
		public ActionResult LogOn(LogOnModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				if (MembershipService.ValidateUser(model.UserName, model.Password))
				{
					FormsService.SignIn(model.UserName, model.RememberMe);
					if (Url.IsLocalUrl(returnUrl))
					{
						return Redirect(returnUrl);
					}
					else
					{
						return Redirect(N2.Find.StartPage.Url);
					}
				}
				else
				{
					ModelState.AddModelError("", "The user name or password provided is incorrect.");
				}
			}

			// If we got this far, something failed, redisplay form
			return View(model);
		}

		// **************************************
		// URL: /Account/LogOff
		// **************************************

		public ActionResult LogOff()
		{
			FormsService.SignOut();

			return Redirect(N2.Find.StartPage.Url);
		}

		// **************************************
		// URL: /Account/Register
		// **************************************

		public ActionResult Register()
		{
			ViewBag.PasswordLength = MembershipService.MinPasswordLength;
			return View();
		}

		[HttpPost]
		public ActionResult Register(RegisterModel model)
		{
			if (ModelState.IsValid)
			{
				// Attempt to register the user
				MembershipCreateStatus createStatus = MembershipService.CreateUser(model.UserName, model.Password, model.Email);

				if (createStatus == MembershipCreateStatus.Success)
				{
					FormsService.SignIn(model.UserName, false /* createPersistentCookie */);
					return Redirect(N2.Find.StartPage.Url);
				}
				else
				{
					ModelState.AddModelError("", AccountValidation.ErrorCodeToString(createStatus));
				}
			}

			// If we got this far, something failed, redisplay form
			ViewBag.PasswordLength = MembershipService.MinPasswordLength;
			return View(model);
		}

		// **************************************
		// URL: /Account/ChangePassword
		// **************************************

		[Authorize]
		public ActionResult ChangePassword()
		{
			ViewBag.PasswordLength = MembershipService.MinPasswordLength;
			return View();
		}

		[Authorize]
		[HttpPost]
		public ActionResult ChangePassword(ChangePasswordModel model)
		{
			if (ModelState.IsValid)
			{
				if (MembershipService.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword))
				{
					return RedirectToAction("ChangePasswordSuccess");
				}
				else
				{
					ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
				}
			}

			// If we got this far, something failed, redisplay form
			ViewBag.PasswordLength = MembershipService.MinPasswordLength;
			return View(model);
		}

		// **************************************
		// URL: /Account/ChangePasswordSuccess
		// **************************************

		public ActionResult ChangePasswordSuccess()
		{
			return View();
		}

	}
}

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/BlogContent.cshtml
@using UnicornCreations
@{
	Content.PrependDefinition(re => 
	{
		re.Container(Defaults.Containers.Metadata, e =>
		{
			e.Name();
		});
	});
}
@Content.Register.Title().Container("Content").Configure(e => e.CssClass = "entry-title").Display()
@{ Content.Register.Summary("Summary", source: "Text"); }
<span class="updated">@Content.Register.PublishedRange().Container("Advanced").Display()</span>
<div class="entry-content">
	@Content.Display.Text
</div>
<span class="author">@Content.Current.Item.SavedBy</span>
@{ Content.Register.Tags("Tags"); }
@if (Content.Has.Tags)
{
	<span class="tags"><label for="tags">@Content.Translate["Tags:"]</label> <span id="tags">@Content.Display.Tags</span></span>
}

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/Content.cshtml
@{
	Content.PrependDefinition(re => 
	{
		re.Container("Metadata", e =>
		{
			e.Name().Title("Path Segment");
		});
	});
}
<div class="container">
    <div class="row">
        <article class="col-xs-12">
            @Content.Register.Title().Container("Content").Configure(e => e.CssClass = "entry-title").Display()

            @Content.Display.Text
        </article>
    </div>
</div>

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/Footer.cshtml
@{
	bool isOutOfStructure = Content.Current.Item == null && !string.IsNullOrEmpty(Request["returnUrl"]);
	using (isOutOfStructure ? Content.BeginScope(Request["returnUrl"]) : Content.BeginScope(Content.Traverse.StartPage))
	{
	   @Content.Display.FooterText
	}
}

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/Head.cshtml
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>@(Content.Has.SeoTitle ? Content.Data.SeoTitle : Content.Data.Title)</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0" />

@Content.Register.Meta("Author").Container("Metadata").Display()
@Content.Register.Meta("Keywords").Container("Metadata").Display()
@Content.Register.Meta("Description").Container("Metadata").Display()

<link href="@Url.ThemedContent("~/Content/Site.css")" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="@Url.ThemedContent("~/favicon.ico")" />
<link rel="apple-touch-icon" href="@Url.ThemedContent("~/apple-touch-icon.png")" />
<link rel="canonical" href="@(Content.Data.Url ?? Request.RawUrl)" />

<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/Header.cshtml
<header id="header" class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
            @{ Html.RenderPartial("LayoutPartials/Logotype"); }
		</div>
		@{ Html.RenderPartial("LayoutPartials/TopNavigation"); }
	</div>
</header>

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/LogOn.cshtml
@if(Request.IsAuthenticated) 
{
	<a href="@Url.Action("LogOff", "Membership")">@Content.Translate["Log off"] <strong>@Context.User.Identity.Name</strong></a>
}
else
{
	var returnUrl = Request["returnUrl"] ?? Content.Data.Url ?? Content.Traverse.StartPage.Url;
	@Html.ActionLink(Content.Translate.Text("Log on"), "LogOn", new { controller = "Membership", returnUrl = returnUrl })
}

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/Logotype.cshtml
@using (Content.BeginScope(Content.Traverse.StartPage))
{
	Content.Render.Image("Logotype").Wrap(@<a href="@Content.Current.Item.Url" title="@Content.Current.Item.Title" class="navbar-brand" id="home">@item.RenderContents()</a>).Render();
}

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/PostContent.cshtml
@{ Html.DroppableZone("PostContent").Render(); }

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/PreContent.cshtml
@using UnicornCreations
@{ Html.DroppableZone("PreContent").Render(); }

@Content.Register.MediaUpload("Image").Configure(fu => { fu.PreferredSize = "wide"; fu.CssClass = "main"; }).Container(Defaults.Containers.Content).Display()

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/Search.cshtml
@{using (Html.BeginForm("Search", null, new { id = "search", item = Content.Traverse.StartPage }, FormMethod.Get, new { id = "searchform" }))
  {
	<input name="q" value="@Content.Translate["Search"]"/>
	<button type="submit"></button>
  }
}

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/SiteMap.cshtml
@Html.ActionLink(Content.Translate.Text("Site map"), Content.Traverse.StartPage, "SiteMap", null, new { id = "sitemapopener" })

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/SubNavigation.cshtml
@using N2.Edit
@{
	int level = 1;
	foreach (var a in Content.Traverse.AncestorsBetween(level, 2)){
		level++;
		@Html.UnorderedList(Content.Traverse.NavigatableChildPages(a).TryAppendCreatorNode(Html.ContentEngine(), a), @<span>@Html.Link(item.Data)</span>, htmlAttributes: new { @class = "submenu menu clearfix level" + level });
	}
}

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/TopNavigation.cshtml
<nav class="collapse navbar-collapse">
@Html.Tree(Content.Parse(Request["returnUrl"]) ?? Content.Traverse.StartPage, htmlAttributes: new { id = "menu", @class = "nav navbar-nav" }, appendCreatorNode: true)
</nav>

UnicornCreations/UnicornCreations/Views/Shared/LayoutPartials/Translations.cshtml
@{ if(Content.Current.Language != null)
{
	<a id="translationsopener" href="@Url.Action("Translations", new { item = Content.Traverse.StartPage, id = Content.Current.Page.ID })">
		<span class="@Content.Current.LanguageCode.Split('-').LastOrDefault() sprite"></span>
		@Content.Current.Language.LanguageTitle.Split('(')[0]
	</a>
}
}